export const federal = {
    CNPJ_INSCRICAO_SITUACAO_CADASTRAL: 'CNPJ_INSCRICAO_SITUACAO_CADASTRAL',
    CERTIDAO_DEBITOS_RELATIVOS_CREDITOS_TRIBUTARIOS_FEDERAIS_DIVIDA_ATIVA_UNIAO: 'CERTIDAO_DEBITOS_RELATIVOS_CREDITOS_TRIBUTARIOS_FEDERAIS_DIVIDA_ATIVA_UNIAO',
    CERTIDAO_NEGATIVA_DEBITOS_TRABALHISTAS: 'CERTIDAO_NEGATIVA_DEBITOS_TRABALHISTAS',
    CERTIFICADO_REGULARIDADE_FGTS: 'CERTIFICADO_REGULARIDADE_FGTS',
    CERTIDAO_NEGATIVA_CONTAS_JULGADAS_IRREGULARES: 'CERTIDAO_NEGATIVA_CONTAS_JULGADAS_IRREGULARES'
}

export const state = {
    CERTIDAO_ESTADUAL_FALENCIA_CONCORDATA: 'CERTIDAO_ESTADUAL_FALENCIA_CONCORDATA',
    CERTIDAO_NEGATIVA_DEBITO_ESTADUAL: 'CERTIDAO_NEGATIVA_DEBITO_ESTADUAL'
}

export const local = {
    CERTIDAO_NEGATIVA_DEBITO_TRIBUTOS_MUNICIPAIS: 'CERTIDAO_NEGATIVA_DEBITO_TRIBUTOS_MUNICIPAIS'
}

export const plans = {
    BASIC: {companiesAllowed: 3},
    MEDIUM: {companiesAllowed: 10},
    ADVANCED: {companiesAllowed: 30}
}


